Gemini 1.0 Pro:
  model_name: gemini-1.0-pro
  group: Gemini
  description: Natural language tasks, multi-turn text and code chat, and code generation
Gemini 1.5 Pro:
  model_name: gemini-1.5-pro
  group: Gemini
  description: Complex reasoning tasks such as code and text generation, text editing, problem solving, data extraction and generation
Gemini 1.5 Flash:
  model_name: gemini-1.5-flash
  group: Gemini
  description: Fast and versatile performance across a diverse variety of tasks
