name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build and Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v3
    - name: Sync dependencies
      shell: bash -l {0}
      run: rye sync
    - name: Build docs
      shell: bash -l {0}
      run: rye run docs
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/_build/html
