name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docs:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v3
    - name: Sync dependencies
      shell: bash -l {0}
      run: rye sync
    - name: Build docs
      shell: bash -l {0}
      run: rye run docs
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/_build/html
